import {
  ONESIGNAL_APP_ID,
  AUTH0_CLIENT_ID,
  AUTH0_DOMAIN,
  MAPBOXGL_ACCCESS_TOKEN,
  MAPBOXGL_DOWNLOAD_TOKEN,
  SENTRY_DSN,
  NEXT_API_URL,
  API_URL,
  APP_URL,
} from '@env';

export const Config = {
  ONESIGNAL_APP_ID: ONESIGNAL_APP_ID,
  AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
  AUTH0_DOMAIN: AUTH0_DOMAIN,
  MAPBOXGL_ACCCESS_TOKEN: MAPBOXGL_ACCCESS_TOKEN,
  MAPBOXGL_DOWNLOAD_TOKEN: MAPBOXGL_DOWNLOAD_TOKEN,
  SENTRY_DSN: SENTRY_DSN,
  NEXT_API_URL: NEXT_API_URL,
  API_URL: API_URL,
  APP_URL: APP_URL,
};
