export const INCIDENT_PAGE_FEATURE_FLAGS = {
  SHOW_RELATED_INCIDENTS_LIST: true,
  SHOW_RELATED_INCIDENTS_ON_MAP: true,
  SHOW_COMBINED_INCIDENT_BOUNDARY: true,
  SHOW_COMBINED_INCIDENT_SUMMARY: true,
} as const;
