FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive \
    TEMP_DIR=/app/tmp \
    LOG_DIR=/app/logs \
    ENVIRONMENT=production \
    DATASET_URL="..." \
    DATABASE_URL="..."

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
        gnupg2 \
        lsb-release \
        unzip \
        gdal-bin \
    && rm -rf /var/lib/apt/lists/*


RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc \
    | apt-key add - \
    && echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
    > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update

RUN apt-get install -y --no-install-recommends \
        postgresql-client-15 \
        postgresql-15-postgis-3 \
        postgis \
    && rm -rf /var/lib/apt/lists/*

ARG GIT_BRANCH=develop
ARG SCRIPT_PATH=scripts/import-npa/natural_protected_areas.sh

RUN wget -q \
        https://raw.githubusercontent.com/Plant-for-the-Planet-org/FireAlert/${GIT_BRANCH}/${SCRIPT_PATH} \
        -O /app/natural_protected_areas.sh \
    && chmod +x /app/natural_protected_areas.sh \
    && mkdir -p "$TEMP_DIR" "$LOG_DIR"

RUN echo '#!/bin/bash' > /app/entrypoint.sh \
    && echo 'exec /app/natural_protected_areas.sh --env "$ENVIRONMENT" --url "$DATASET_URL" --dburl "$DATABASE_URL" "$@"' >> /app/entrypoint.sh \
    && chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
