name: Test build on Ubuntu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn nativeapp install

      - name: Linting
        run: yarn nativeapp lint:errors
