name: Test build on Ubuntu

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Caching node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-filealert-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-filealert-

      - name: Upgrade npm to latest version
        run: sudo npm i -g npm@latest

      - name: Install react-native CLI
        run: "sudo npm install -g react-native-cli"

      - name: Install npm dependencies
        run: npm install

      - name: Linting
        run: npm run lint:errors

      - name: Setting Environment Variables
        env:
          MAPBOXGL_ACCCESS_TOKEN: ${{ secrets.MAPBOXGL_ACCCESS_TOKEN }}
          BUGSNAP_CLIENT_KEY: ${{ secrets.BUGSNAP_CLIENT_KEY }}
        run: |
          echo "MAPBOXGL_ACCCESS_TOKEN=$MAPBOXGL_ACCCESS_TOKEN" >> .env
          echo "BUGSNAP_CLIENT_KEY=$BUGSNAP_CLIENT_KEY" >> .env

      - name: Build Android app
        run: |
          react-native bundle \
              --platform android \
              --dev false \
              --entry-file index.js \
              --bundle-output android-release.bundle \
              --sourcemap-output android-release.bundle.map
      - name: Build iOS app
        run: |
          react-native bundle \
              --platform ios \
              --dev false \
              --entry-file index.js \
              --bundle-output ios-release.bundle \
              --sourcemap-output ios-release.bundle.map
