export {default as Home} from './Home/Home';
export {default as Login} from './Login/Login';
export {default as Otp} from './Verification/Otp';
export {default as Settings} from './Settings/Settings';
export {default as Verification} from './Verification/Verification';
export {default as UploadPolygon} from './uploadPolygon/UploadPolygon';
export {default as CreatePolygon} from './CreatePolygon/CreatePolygon';
export {default as SelectLocation} from './selectLocation/SelectLocation';
export {default as ProtectedAreas} from './ProtectedAreas/ProtectedAreas';
